SET DBS = '<% dbsname %>';
SET XMA = '<% depname %>';
SET SVC = '<% depname %>_SVC';
SET USR = '<% depname %>_USR';
SET ROL = '<% depname %>_ROL';
SET CPL = '<% depname %>_CPL';
SET VWH = '<% depname %>_VWH';
SET NRL = '<% depname %>_NRL';
SET EAI = '<% depname %>_EAI';


---------------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
USE DATABASE IDENTIFIER($DBS);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($XMA);
USE SCHEMA IDENTIFIER($XMA);

DROP USER IF EXISTS IDENTIFIER($USR);
DROP ROLE IF EXISTS IDENTIFIER($ROL);

ALTER SERVICE IF EXISTS IDENTIFIER($SVC) SUSPEND;
DROP SERVICE IF EXISTS IDENTIFIER($SVC);

ALTER COMPUTE POOL IF EXISTS IDENTIFIER($CPL) SUSPEND;
DROP COMPUTE POOL IF EXISTS IDENTIFIER($CPL);

DROP WAREHOUSE IF EXISTS IDENTIFIER($VWH);

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS IDENTIFIER($EAI);
DROP NETWORK RULE IF EXISTS IDENTIFIER($NRL);

DROP SCHEMA IF EXISTS IDENTIFIER($XMA);
